version: '3'

services:

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: parser
      MYSQL_USER: parser_admin
      MYSQL_PASSWORD: 123456
    ports:
          - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: leonovandreydpo43/sled-app:2.0.3
    #build: .
    container_name: app-container
    ports:
        - 80:80
    volumes:
      - ./logs:/home/leonovav/logs
      - app_data:/var/www/html
    environment:
      CUSTOM_LOG_DIR: /home/leonovav/logs/custom-log.txt
    depends_on:
        - db

volumes:
  app_data:
  db_data:        