version: '3'

networks:
  Leonov:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.6.0/24
          gateway: 10.20.6.1

services:

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: parser
      MYSQL_USER: parser_admin
      MYSQL_PASSWORD: 123456
    ports:
          - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      Leonov:
        ipv4_address: 10.20.6.20
  app:
    image: leonovandreydpo43/sled-app:latest
    container_name: app-container
    ports:
        - 80:80
    volumes:
      - ./logs:/home/leonovav/logs
      - app_data:/var/www/html
    environment:
      CUSTOM_LOG_DIR: /home/leonovav/logs/custom-log.txt
    depends_on:
        - db
    networks:
      Leonov:
        ipv4_address: 10.20.6.10

volumes:
  app_data:
  db_data:        
