name: Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout код
        uses: actions/checkout@v4
        
      - name: Установка тега версии образа
        run: |
          TAG=$(date +"%Y%m%d-%H%M%S")
          echo "TAG=$TAG" >> $GITHUB_ENV
          
      - name: Сборка образа
        run: docker build --no-cache -t leonovandreydpo43/sled-app:${{ env.TAG }} .
        
      - name: Авторизация и отправкка образа в Docker Hub        
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push leonovandreydpo43/sled-app:${{ env.TAG }}          
      
      - name: Деплой на сервер через SSH  
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}  # или private_key
          port: ${{ secrets.SSH_PORT }}
          script: |

            export TAAAAAAG=${{ env.TAG }}
            
            echo "Подключаемся к серверу и обновляем проект..."
            cd /home/sledopyt || (echo "Папка не найдена" && exit 1)

            echo "Сбрасываем локальные изменения..."
            git reset --hard HEAD
            git clean -fd
            
            echo "Стягиваем последние изменения..."
            git pull origin main
  
            echo "Останавливаем старые контейнеры..."
            docker-compose down

            echo "Удаляем том с приложением"
            docker volume rm sledopyt_app_data
            
            echo "Скачиваем новый образ..."
            docker-compose pull
            
            echo "Запускаем сервисы..."
            docker-compose up -d --build --force-recreate

            echo "Очистка неиспользуемых образов и контейнеров"
            docker container prune -f
            docker image prune -a -f
