name: Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Сборка образа
        run: docker build ./my-app -t leonovandreydpo43/sled-app:latest

      - name: Авторизация и отправкка образа в Docker Hub        
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ DOCKER_HUB_TOKEN }}
          docker push leonovandreydpo43/sled-app:latest
      
      - name: Подключение к серверу через SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -y
          ${{ secrets.SSH_PASSWORD }} -y
        
      - name: Деплой на сервер через SSH  
        run: |
          echo "Подключаемся к серверу и обновляем проект..."
          cd /home || (echo "Папка не найдена" && exit 1)

          echo "Стягиваем последние изменения..."
          git pull origin main

          echo "Останавливаем старые контейнеры..."
          docker-compose down

          echo "Скачиваем новый образ..."
          docker-compose pull

          echo "Запускаем сервисы..."
          docker-compose up -d
