name: Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Сборка образа
        run: docker build --no-cache -t leonovandreydpo43/sled-app:latest .

      - name: Авторизация и отправкка образа в Docker Hub        
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push leonovandreydpo43/sled-app:latest
        
      - name: Деплой на сервер через SSH  
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}  # или private_key
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Подключаемся к серверу и обновляем проект..."
            cd /home/sledopyt || (echo "Папка не найдена" && exit 1)

            echo "Сбрасываем локальные изменения..."
            git reset --hard HEAD
            git clean -fd
            
            echo "Стягиваем последние изменения..."
            git pull origin main
  
            echo "Останавливаем старые контейнеры..."
            docker-compose down
  
            echo "Скачиваем новый образ..."
            docker-compose pull
  
            echo "Запускаем сервисы..."
            docker-compose up -d
