name: Deploy with Docker Compose

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Установить Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Собрать и отправить образ на Docker Hub
        run: |
          docker-compose build
          docker-compose push

      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Подключаемся к серверу и обновляем проект..."
            cd /home/user/myproject || (echo "Папка не найдена" && exit 1)

            echo "Стягиваем последние изменения..."
            git pull origin main

            echo "Останавливаем старые контейнеры..."
            docker-compose down

            echo "Скачиваем новый образ..."
            docker-compose pull

            echo "Запускаем сервисы..."
            docker-compose up -d
